language: rust
rust: stable

before_script:
  - curl -sSLf https://github.com/rust-lang-nursery/mdBook/releases/download/v0.2.1/mdbook-v0.2.1-x86_64-unknown-linux-gnu.tar.gz | tar xzf -
  - chmod +x ./mdbook
  - mkdir -p $HOME/.local/bin
  - mv ./mdbook $HOME/.local/bin/
  - export PATH=$HOME/.local/bin:$PATH

script:
  - mdbook build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  repo: finchers-rs/guide
  target_branch: gh-pages
  local_dir: build
  on:
    branch: master
