[book]
title = "Finchers Users Guide"
description = "The user guide of Finchers"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com"]
multilingual = false
src = "src"

[build]
build-dir = "build"
create-missing = false
